name: Report a bug
description: when something isn't working right.
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for submitting a bug report! Please answer the following questions:
  - type: 'textarea'
    attributes:
      label: 'What is your Quests version / build number (do _not_ say "latest")?'
      description: 'You can find this using the `/quests info` command.'
      placeholder: 'The version used is...'
    validations:
      required: true
  - type: 'textarea'
    attributes:
      label: 'Describe the problem and how to replicate it. Any console errors to share?'
      description: 'Paste the error into the field below.'
      render: shell
    validations:
      required: true
  - type: 'textarea'
    attributes:
      label: 'If applicable, can you provide an example quest from quests.yml?'
      description: 'Do not upload the file itself.'
      render: shell
    validations:
      required: false
