blank_issues_enabled: false
contact_links:
  - name: Documentation
    about: 'Check the Quests docs before reporting issues.'
    url: 'https://pikamug.gitbook.io/quests/'
  - name: Discord
    about: 'Ask your questions here!'
    url: 'https://discordapp.com/invite/QdJAv2G7qg'
  - name: Development Builds
    about: 'Remember to make a backup before updating.'
    url: 'https://ci.codemc.io/job/PikaMug/job/Quests/'
